#!/bin/bash

cd "$(dirname "$0")"

rm -f *.c *.h

for xml in ../../third_party/xcbproto/src/*.xml; do
    "$1" ../../third_party/libxcb/src/c_client.py \
        -c "libxcb 1.15" \
        -l "X Version 11" \
        -s "" \
        -p ../../third_party/xcbproto \
        "$xml"
done

rm -rf man
