#!/bin/sh

substrate_dir="$(realpath "$(dirname "$0")")"

docker run -it --rm \
    -v "$substrate_dir:/substrate:ro" \
    -v "$1:/build" \
    "$(docker build -q "$substrate_dir/docker/yocto_host")"
